### ISSUE TITLE
Mulighet for å lese ut innslag-logg

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMsupport#7]
ca
SELECT *, FROM_UNIXTIME(`log_time`)
FROM `ukmno_smartukm_log` AS `l`
JOIN `ukmno_smartukm_log_codes` AS `lc` ON(`lc`.`log_code` = `l`.`log_code`)
WHERE `log_b_id` = '94511'

**Comment by AsgeirSH** [comment]
Duplicate UKMNorge/UKMlog#4 ? Eller vil vi også ha samme greia i support-dashboardet?

**Comment by mariusmandal** [comment]
Skip supportlog - vi søker aldri loggen etter gitt band ID lengre, det var relatert til ukmpamelding-support.. :)
